---
# tasks file for ansible-motd
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: main | Configuring MOTD
  template:
    src: "etc/motd.j2"
    dest: "/etc/motd"
  become: true
