---
# tasks file for ansible-motd
- name: main | Configuring MOTD
  template:
    src: "etc/motd.j2"
    dest: "/etc/motd"
  become: true

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: main | Configuring Custom MOTD Scripts
  template:
    src: "etc/update-motd.d/{{ item }}.j2"
    dest: "{{ motd_default_dir }}/{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
  become: true
  with_items: '{{ motd_custom_scripts }}'
  when: motd_enable_custom_scripts
