---
# tasks file for ansible-motd
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: main | Configuring MOTD
  template:
    src: etc/motd.j2
    dest: /etc/motd
  become: true
