---
- name: redhat | Installing Pre-Reqs
  yum:
    name:
      - bind-utils
    state: present
  become: true
  register: results
  until: results is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  dnf:
    name:
      - bind-utils
      - libselinux-python
    state: present
  become: true
  register: results
  until: results is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Configuring Custom MOTD Scripts
  template:
    src: etc/motd.sh.j2
    dest: /etc/motd.sh
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true
  when: motd_enable_custom_scripts|bool

- name: redhat | Enabling Custom MOTD Script
  lineinfile:
    dest: /etc/profile
    regexp: "^/etc/motd.sh"
    line: /etc/motd.sh
    state: present
  become: true
  when: motd_enable_custom_scripts|bool
